import { GetStaticPropsContext, InferGetStaticPropsType } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { useTranslation } from "next-i18next"
import { serverSideTranslations } from "next-i18next/serverSideTranslations"

export default function Home(_props: InferGetStaticPropsType<typeof getStaticProps>) {
  const router = useRouter()
  const { t } = useTranslation("home")

  const handleLangToggle = (newLocale: string) => {
    const { pathname, asPath, query } = router
    router.push({ pathname, query }, asPath, { locale: newLocale })
  }

  const changeTo = router.locale === "ko" ? "en" : "ko"

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => handleLangToggle(changeTo)}>change lang</button>
        <div>{t("country", { changeTo })}</div>
        <div>{t("welcome", { changeTo })}</div>
      </main>
    </>
  )
}

export const getStaticProps = async ({ locale }: GetStaticPropsContext) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || "ko", ["common", "home"])), //  === "ko" ? "en" : "ko"
    },
  }
}
