import { GetStaticPropsContext, InferGetStaticPropsType } from "next"
import Head from "next/head"
import { useTranslation } from "next-i18next"
import { serverSideTranslations } from "next-i18next/serverSideTranslations"

export default function Home(_props: InferGetStaticPropsType<typeof getStaticProps>) {
  const { t } = useTranslation("home")

  console.log(t("h1"))
  console.log(t("name"))
  console.log(t("description"))

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>my first next app</div>
      </main>
    </>
  )
}

export const getStaticProps = async ({ locale }: GetStaticPropsContext) => {
  console.log(locale)

  return {
    props: {
      ...(await serverSideTranslations(locale || "ko", ["common", "home"])), //  === "ko" ? "en" : "ko"
    },
  }
}
